// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState, useEffect, useCallback } from 'react';
import { fetchWeather } from '../api';

const CurrentWeather = ({ city, coordinates, unit, setWeatherIcon }) => {
  const [weather, setWeather] = useState(null);

  const updateWeatherIcon = useCallback((icon) => {
    setWeatherIcon(icon);
  }, [setWeatherIcon]);

  useEffect(() => {
    if (coordinates) {
      fetchWeather(`${coordinates.lat},${coordinates.lon}`).then((response) => {
        setWeather(response.data);
        updateWeatherIcon(response.data.current.condition.icon);
      });
    } else if (city) {
      fetchWeather(city).then((response) => {
        setWeather(response.data);
        updateWeatherIcon(response.data.current.condition.icon);
      });
    }
  }, [city, coordinates, updateWeatherIcon]);

  if (!weather) return <div>Loading...</div>;

  const temp = unit === 'C' ? weather.current.temp_c : weather.current.temp_f;

  return (
    <div className="current-weather">
      {/* <h2>{weather.location.name}</h2> */}
      {/* <p>{weather.location.localtime}</p> */}
      <div className="weather-details">
        <div className="weather-icon">
          <img src={weather.current.condition.icon} alt="Weather Icon" />
        </div>
        <div className="weather-info">
          <p className="temperature">{temp}°{unit}</p>
          <p>{weather.current.condition.text}</p>
          <p>Humidity: {weather.current.humidity}%</p>
          <p>Cloudy: {weather.current.cloud}%</p>
          <p>Wind: {weather.current.wind_kph} kph</p>
        </div>
      </div>
    </div>
  );
};

export default CurrentWeather;
