// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState, useEffect } from 'react';
import { fetchForecast } from '../api';

const FiveDayForecast = ({ city, coordinates, unit }) => {
  const [forecast, setForecast] = useState(null);

  useEffect(() => {
    if (coordinates) {
      fetchForecast(`${coordinates.lat},${coordinates.lon}`).then((response) => setForecast(response.data));
    } else if (city) {
      fetchForecast(city).then((response) => setForecast(response.data));
    }
  }, [city, coordinates]);

  if (!forecast) return <div>Loading...</div>;

  return (
    <div className="five-day-forecast">
      <table className="weather-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Min Temp</th>
            <th>Max Temp</th>
            <th>Condition</th>
            <th>Icon</th>
          </tr>
        </thead>
        <tbody>
          {forecast.forecast.forecastday.map((day, index) => (
            <tr key={index}>
              <td>{day.date}</td>
              <td>{unit === 'C' ? day.day.mintemp_c : day.day.mintemp_f}°{unit}</td>
              <td>{unit === 'C' ? day.day.maxtemp_c : day.day.maxtemp_f}°{unit}</td>
              <td>{day.day.condition.text}</td>
              <td><img src={day.day.condition.icon} alt="Weather Icon" className="weather-icon" /></td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default FiveDayForecast;
