// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState, useEffect } from 'react';
import { fetchForecast } from '../api';

const HourlyForecast = ({ city, coordinates, unit }) => {
  const [forecast, setForecast] = useState(null);

  useEffect(() => {
    if (coordinates) {
      fetchForecast(`${coordinates.lat},${coordinates.lon}`).then((response) => setForecast(response.data));
    } else if (city) {
      fetchForecast(city).then((response) => setForecast(response.data));
    }
  }, [city, coordinates]);

  if (!forecast) return <div>Loading...</div>;

  return (
    <div className="hourly-forecast">
      <table className="weather-table">
        <thead>
          <tr>
            <th>Time</th>
            <th>Temperature</th>
            <th>Condition</th>
            <th>Icon</th>
          </tr>
        </thead>
        <tbody>
          {forecast.forecast.forecastday[0].hour.map((hour, index) => (
            <tr key={index}>
              <td>{hour.time}</td>
              <td>{unit === 'C' ? hour.temp_c : hour.temp_f}°{unit}</td>
              <td>{hour.condition.text}</td>
              <td><img src={hour.condition.icon} alt="Weather Icon" className="weather-icon" /></td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default HourlyForecast;
