// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState } from 'react';
import { FaSearch } from 'react-icons/fa';

const Search = ({ setCity }) => {
  const [input, setInput] = useState('');

  const handleSearch = () => {
    setCity(input);
  };

  return (
    <div className="search">
      <FaSearch className="search-icon" />
      <input
        type="text"
        placeholder="Enter city name"
        value={input}
        onChange={(e) => setInput(e.target.value)}
      />
      <button onClick={handleSearch}>Search</button>
    </div>
  );
};

export default Search;
