// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState, useEffect } from 'react';
import CurrentWeather from '../components/CurrentWeather';
import HourlyForecast from '../components/HourlyForecast';
import FiveDayForecast from '../components/FiveDayForecast';
import Search from '../components/Search';

const Home = () => {
  const [city, setCity] = useState('');
  const [coordinates, setCoordinates] = useState(null);
  const [unit, setUnit] = useState('C'); // 'C' for Celsius, 'F' for Fahrenheit
  const [weatherIcon, setWeatherIcon] = useState('');

  useEffect(() => {
    if (!city) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          setCoordinates({
            lat: position.coords.latitude,
            lon: position.coords.longitude,
          });
        },
        (error) => {
          console.error('Error getting geolocation', error);
        }
      );
    }
  }, [city]);

  const handleToggle = () => {
    setUnit(unit === 'C' ? 'F' : 'C');
  };

  return (
    <div className="container">
      <div className="left-panel">
        <Search setCity={setCity} />
        <div className="city-info">
          <h2>{city || 'Delhi Paharganj'}</h2>
          <p>{new Date().toLocaleDateString()}</p>
          {weatherIcon && <img src={weatherIcon} alt="Weather Icon" className="weather-icon" />}
        </div>
      </div>
      <div className="right-panel">
        <div className="toggle-container">
          <label>Switch to Fahrenheit</label>
          <label className="toggle-switch">
            <input type="checkbox" checked={unit === 'F'} onChange={handleToggle} />
            <span className="slider"></span>
          </label>
        </div>
        <div className="weather-section">
          <p>Current Weather Details</p>
          <CurrentWeather city={city} coordinates={coordinates} unit={unit} setWeatherIcon={setWeatherIcon} />
        </div>
        <div className="weather-section">
          <p>Hourly Forecast</p>
          <HourlyForecast city={city} coordinates={coordinates} unit={unit} />
        </div>
        <div className="weather-section">
          <p>Five Day Forecast</p>
          <FiveDayForecast city={city} coordinates={coordinates} unit={unit} />
        </div>
      </div>
    </div>
  );
};

export default Home;
