// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState, useEffect, useCallback } from 'react';
import CurrentWeather from '../components/CurrentWeather';
import HourlyForecast from '../components/HourlyForecast';
import FiveDayForecast from '../components/FiveDayForecast';
import Search from '../components/Search';
import axios from 'axios';

const Home = () => {
  const [city, setCity] = useState('');
  const [coordinates, setCoordinates] = useState(null);
  const [unit, setUnit] = useState('C'); // 'C' for Celsius, 'F' for Fahrenheit
  const [weatherIcon, setWeatherIcon] = useState('');
  const [temperature, setTemperature] = useState('');

  const fetchCityNameAndTemperature = useCallback(async (coords) => {
    try {
      const weatherResponse = await axios.get(`https://api.weatherapi.com/v1/current.json?key=fcf149ef20f1484ab4f172906250304&q=${coords.lat},${coords.lon}`);
      const cityName = weatherResponse.data.location.name;
      setCity(cityName);

      const temp = unit === 'C' ? weatherResponse.data.current.temp_c : weatherResponse.data.current.temp_f;
      setTemperature(`${temp}°${unit}`);
      setWeatherIcon(weatherResponse.data.current.condition.icon);
    } catch (error) {
      console.error('Error fetching city name and temperature', error);
      setCity('Your Location');
      setTemperature('');
    }
  }, [unit]);

  useEffect(() => {
    if (!city) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          const coords = {
            lat: position.coords.latitude,
            lon: position.coords.longitude,
          };
          setCoordinates(coords);
          fetchCityNameAndTemperature(coords);
        },
        (error) => {
          console.error('Error getting geolocation', error);
        }
      );
    }
  }, [city, fetchCityNameAndTemperature]);

  const handleToggle = () => {
    setUnit(unit === 'C' ? 'F' : 'C');
    if (coordinates) {
      fetchCityNameAndTemperature(coordinates);
    }
  };

  return (
    <div className="container">
      <div className="left-panel">
        <Search setCity={setCity} />
        <div className="city-info">
          <h2>{city}</h2>
          <p>{new Date().toLocaleDateString()}</p>
          {weatherIcon && <img src={weatherIcon} alt="Weather Icon" className="weather-icon" />}
          <p className="temperature">{temperature}</p>
        </div>
      </div>
      <div className="right-panel">
        <div className="toggle-container">
          <label>Switch to Fahrenheit</label>
          <label className="toggle-switch">
            <input type="checkbox" checked={unit === 'F'} onChange={handleToggle} />
            <span className="slider"></span>
          </label>
        </div>
        <div className="weather-section">
          <p>Current Weather Details</p>
          <CurrentWeather city={city} coordinates={coordinates} unit={unit} setWeatherIcon={setWeatherIcon} />
        </div>
        <div className="weather-section">
          <p>Hourly Forecast</p>
          <HourlyForecast city={city} coordinates={coordinates} unit={unit} />
        </div>
        <div className="weather-section">
          <p>Five Day Forecast</p>
          <FiveDayForecast city={city} coordinates={coordinates} unit={unit} />
        </div>
      </div>
    </div>
  );
};

export default Home;
