// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState } from 'react';
import { useLocation } from 'react-router-dom';
import CurrentWeather from '../components/CurrentWeather';
import HourlyForecast from '../components/HourlyForecast';
import FiveDayForecast from '../components/FiveDayForecast';
import Search from '../components/Search';

const useQuery = () => {
  return new URLSearchParams(useLocation().search);
};

const SearchPage = () => {
  const query = useQuery();
  const city = query.get('city');
  const [unit, setUnit] = useState('C'); // 'C' for Celsius, 'F' for Fahrenheit
  const [weatherIcon, setWeatherIcon] = useState('');

  const handleToggle = () => {
    setUnit(unit === 'C' ? 'F' : 'C');
  };

  return (
    <div className="container">
      <div className="left-panel">
        <Search setCity={() => {}} />
        <div className="city-info">
          <h2>{city}</h2>
          <p>{new Date().toLocaleDateString()}</p>
          {weatherIcon && <img src={weatherIcon} alt="Weather Icon" className="weather-icon" />}
        </div>
      </div>
      <div className="right-panel">
        <div className="toggle-container">
          <label>Switch to Fahrenheit</label>
          <label className="toggle-switch">
            <input type="checkbox" checked={unit === 'F'} onChange={handleToggle} />
            <span className="slider"></span>
          </label>
        </div>
        <div className="weather-section">
          <p>Current Weather Details</p>
          <CurrentWeather city={city} unit={unit} setWeatherIcon={setWeatherIcon} />
        </div>
        <div className="weather-section">
          <p>Hourly Forecast</p>
          <HourlyForecast city={city} unit={unit} />
        </div>
        <div className="weather-section">
          <p>Five Day Forecast</p>
          <FiveDayForecast city={city} unit={unit} />
        </div>
      </div>
    </div>
  );
};

export default SearchPage;
